GlobalSettings:
  #The username that uses the token
  username: "admin"
  
  #The path to the file where is stored the token
  tokenPath: "/home/pi/Documents/Secret/.tokenIUB"
  
  #The url that handles the api requests
  urlHandler: "https://iceuploadbank.ddns.net"
  
  #The accuracy level on logging
  logLevel: "INFO"
  
  #Number of files to upload per request
  upload_per_request: 4
  
  #The list of material to upload
  material_list: ['film', 'serietv']
